In [49]:
import pandas as pd
import numpy as np
from datetime import datetime, timedelta
import warnings
warnings.filterwarnings('ignore')

In [50]:
from google.colab import files
uploaded = files.upload()

Saving student.csv to student (1).csv

In [51]:
import pandas as pd

# Assuming 'student.csv' is the file name
df = pd.read_csv('/content/student.csv')
print(df.head())  # Display the first few rows of the dataframe

   รหัสนักศึกษา      ชื่อ  อายุ   เพศ             คณะ   GPA  ส่วนสูง_cm  \
0         64001     สมชาย  20.0   ชาย     วิทยาศาสตร์  3.21       170.0
1         64002    สมหญิง  21.0  หญิง           วิทย์  3.45       165.0
2         64003       NaN   NaN  Male         Science  3.67       175.0
3         64004  สมศักดิ์  22.0     ช  คณะวิทยาศาสตร์ -1.00       168.0
4         64005      สมใจ  19.0     ญ           วิศวะ  3.89       160.0

   น้ำหนัก_kg  ชั่วโมงเรียน_ต่อสัปดาห์ วันที่ลงทะเบียน
0        65.0                     15.0      2024-02-06
1        58.0                     20.0      2023-12-17
2         NaN                     25.0      2024-01-08
3        70.0                     10.0      2024-01-28
4        52.0                     30.0      2024-01-14

In [52]:
np.random.seed(42)

ให้ผลลัพธ์ที่สามารถทำซ้ำได้ (reproducible) โดยการตั้งค่า seed เป็น 42 นั้นจะทำให้ผลลัพธ์ที่ออกมาเหมือนเดิมทุกครั้งที่รันโค้ด

In [53]:
student_data = {
    'รหัสนักศึกษา': [f'64{str(i).zfill(3)}' for i in range(1, 21)],
    'ชื่อ': ['สมชาย', 'สมหญิง', None, 'สมศักดิ์', 'สมใจ', 'กานต์', 'กิตติ',
             'จิรา', 'ชนาธิป', 'ดารา', 'ธีระ', 'นภา', 'บุญมี', 'ปรีชา',
             'พิมพ์', 'ภูมิ', 'มานี', 'ยุพา', 'รัตนา', 'ลัดดา'],
    'อายุ': [20, 21, None, 22, 19, 150, 21, 20, 23, 21,  # 150 = outlier
            None, 22, 20, 21, 22, 19, 20, 21, None, 22],
    'เพศ': ['ชาย', 'หญิง', 'Male', 'ช', 'ญ', 'ชาย', 'หญิง', 'F', 'M', 'หญิง',
            None, 'ชาย', 'หญิง', 'ชาย', 'Female', 'ช', 'ญ', 'หญิง', 'ชาย', None],
    'คณะ': ['วิทยาศาสตร์', 'วิทย์', 'Science', 'คณะวิทยาศาสตร์', 'วิศวะ',
            'Engineering', 'วิศวกรรม', 'ศิลปศาสตร์', 'Arts', 'ศิลป์',
            None, 'วิทย์', 'วิศวฯ', 'Liberal Arts', 'Sci',
            'วิทยาศาสตร์', 'วิศวกรรมศาสตร์', None, 'ศิลปศาสตร์', 'Science'],
    'GPA': [3.21, 3.45, 3.67, -1, 3.89, 3.12, 4.5, 2.98, 3.34, 3.56,
            3.78, None, 3.23, 3.45, 3.67, 3.89, 3.01, 3.23, None, 3.45],
    'ส่วนสูง_cm': [170, 165, 175, 168, 160, 172, 158, 180, 163, 167,
                  None, 171, 169, 164, 162, 173, 166, 161, 174, 168],
    'น้ำหนัก_kg': [65, 58, None, 70, 52, 75, 48, 82, 55, 60,
                  68, None, 72, 54, 56, 78, 62, 50, 76, 64],
    'ชั่วโมงเรียน_ต่อสัปดาห์': [15, 20, 25, 10, 30, 12, 35, 18, 22, 28,
                              None, 16, 24, 19, 26, 14, 21, 27, None, 23]
}

สร้าง student_data ซึ่งประกอบด้วยรายละเอียดของนักศึกษาในฟิลด์ต่าง ๆ เช่น รหัสนักศึกษา, ชื่อ, อายุ, เพศ, คณะ, GPA, ส่วนสูง, น้ำหนัก และชั่วโมงเรียน ต่อสัปดาห์

In [54]:

student_df = pd.DataFrame(student_data)


print(student_df)

   รหัสนักศึกษา      ชื่อ   อายุ     เพศ             คณะ   GPA  ส่วนสูง_cm  \
0         64001     สมชาย   20.0     ชาย     วิทยาศาสตร์  3.21       170.0
1         64002    สมหญิง   21.0    หญิง           วิทย์  3.45       165.0
2         64003      None    NaN    Male         Science  3.67       175.0
3         64004  สมศักดิ์   22.0       ช  คณะวิทยาศาสตร์ -1.00       168.0
4         64005      สมใจ   19.0       ญ           วิศวะ  3.89       160.0
5         64006     กานต์  150.0     ชาย     Engineering  3.12       172.0
6         64007     กิตติ   21.0    หญิง        วิศวกรรม  4.50       158.0
7         64008      จิรา   20.0       F      ศิลปศาสตร์  2.98       180.0
8         64009    ชนาธิป   23.0       M            Arts  3.34       163.0
9         64010      ดารา   21.0    หญิง           ศิลป์  3.56       167.0
10        64011      ธีระ    NaN    None            None  3.78         NaN
11        64012       นภา   22.0     ชาย           วิทย์   NaN       171.0
12        64013     บุญมี   20.0    หญิง           วิศวฯ  3.23       169.0
13        64014     ปรีชา   21.0     ชาย    Liberal Arts  3.45       164.0
14        64015     พิมพ์   22.0  Female             Sci  3.67       162.0
15        64016      ภูมิ   19.0       ช     วิทยาศาสตร์  3.89       173.0
16        64017      มานี   20.0       ญ  วิศวกรรมศาสตร์  3.01       166.0
17        64018      ยุพา   21.0    หญิง            None  3.23       161.0
18        64019     รัตนา    NaN     ชาย      ศิลปศาสตร์   NaN       174.0
19        64020     ลัดดา   22.0    None         Science  3.45       168.0

    น้ำหนัก_kg  ชั่วโมงเรียน_ต่อสัปดาห์
0         65.0                     15.0
1         58.0                     20.0
2          NaN                     25.0
3         70.0                     10.0
4         52.0                     30.0
5         75.0                     12.0
6         48.0                     35.0
7         82.0                     18.0
8         55.0                     22.0
9         60.0                     28.0
10        68.0                      NaN
11         NaN                     16.0
12        72.0                     24.0
13        54.0                     19.0
14        56.0                     26.0
15        78.0                     14.0
16        62.0                     21.0
17        50.0                     27.0
18        76.0                      NaN
19        64.0                     23.0

สร้าง DataFrame จาก student_data เเละเเสดงผล

In [55]:
student_df.shape

(20, 9)

ดูขนาดของ student_dfประกอบด้วยจำนวนแถวและจำนวนคอลัมน์

In [56]:
student_df.head(3)

,รหัสนักศึกษา,ชื่อ,อายุ,เพศ,คณะ,GPA,ส่วนสูง_cm,น้ำหนัก_kg,ชั่วโมงเรียน_ต่อสัปดาห์
0,64001,สมชาย,20.0,ชาย,วิทยาศาสตร์,3.21,170.0,65.0,15.0
1,64002,สมหญิง,21.0,หญิง,วิทย์,3.45,165.0,58.0,20.0
2,64003,None,NaN,Male,Science,3.67,175.0,NaN,25.0

แสดงข้อมูล 3 แถวแรก

In [57]:
base_date = datetime(2024, 1, 15)

สร้างวัตถุวันที่และเวลา เป็นวันที่ 15 มกราคม 2024

In [58]:
base_date

datetime.datetime(2024, 1, 15, 0, 0)

In [59]:
base_date = datetime(2024, 1, 15)
student_df['วันที่ลงทะเบียน'] = [
    base_date + timedelta(days=np.random.randint(-30, 30))
    for _ in range(20)
]

สร้างคอลัมน์ใหม่ใน DataFrame student_df ชื่อว่า 'วันที่ลงทะเบียน' โดยที่แต่ละค่าจะถูกสร้างจากการเพิ่มหรือลบวันจาก base_date (วันที่ 15 มกราคม 2024) ตามจำนวนวันที่สุ่มจากช่วง -30 ถึง 30 วัน ด้วยการใช้ np.random.randint(-30, 30) สำหรับแต่ละแถวใน DataFrame 20 แถว

In [60]:
student_df

,รหัสนักศึกษา,ชื่อ,อายุ,เพศ,คณะ,GPA,ส่วนสูง_cm,น้ำหนัก_kg,ชั่วโมงเรียน_ต่อสัปดาห์,วันที่ลงทะเบียน
0,64001,สมชาย,20.0,ชาย,วิทยาศาสตร์,3.21,170.0,65.0,15.0,2024-01-23
1,64002,สมหญิง,21.0,หญิง,วิทย์,3.45,165.0,58.0,20.0,2024-02-05
2,64003,None,NaN,Male,Science,3.67,175.0,NaN,25.0,2024-01-13
3,64004,สมศักดิ์,22.0,ช,คณะวิทยาศาสตร์,-1.00,168.0,70.0,10.0,2023-12-30
4,64005,สมใจ,19.0,ญ,วิศวะ,3.89,160.0,52.0,30.0,2024-01-27
5,64006,กานต์,150.0,ชาย,Engineering,3.12,172.0,75.0,12.0,2023-12-23
6,64007,กิตติ,21.0,หญิง,วิศวกรรม,4.50,158.0,48.0,35.0,2024-01-05
7,64008,จิรา,20.0,F,ศิลปศาสตร์,2.98,180.0,82.0,18.0,2024-01-23
8,64009,ชนาธิป,23.0,M,Arts,3.34,163.0,55.0,22.0,2024-02-11
9,64010,ดารา,21.0,หญิง,ศิลป์,3.56,167.0,60.0,28.0,2024-01-03
10,64011,ธีระ,NaN,None,None,3.78,NaN,68.0,NaN,2024-01-07
11,64012,นภา,22.0,ชาย,วิทย์,NaN,171.0,NaN,16.0,2023-12-26
12,64013,บุญมี,20.0,หญิง,วิศวฯ,3.23,169.0,72.0,24.0,2023-12-26
13,64014,ปรีชา,21.0,ชาย,Liberal Arts,3.45,164.0,54.0,19.0,2024-01-08
14,64015,พิมพ์,22.0,Female,Sci,3.67,162.0,56.0,26.0,2024-02-06
15,64016,ภูมิ,19.0,ช,วิทยาศาสตร์,3.89,173.0,78.0,14.0,2024-01-20
16,64017,มานี,20.0,ญ,วิศวกรรมศาสตร์,3.01,166.0,62.0,21.0,2024-01-24
17,64018,ยุพา,21.0,หญิง,None,3.23,161.0,50.0,27.0,2024-01-08
18,64019,รัตนา,NaN,ชาย,ศิลปศาสตร์,NaN,174.0,76.0,NaN,2023-12-18
19,64020,ลัดดา,22.0,None,Science,3.45,168.0,64.0,23.0,2024-01-06

In [61]:
print("="*50)
print("🎯 ข้อมูลหลัก (Master Dataset) ที่จะใช้ตลอดบทเรียน")
print("="*50)
print(student_df)  # หรือ df_master หากใช้ชื่ออื่น
print("\n📊 สรุปปัญหาที่พบในข้อมูล:")
print(f"- ค่าหายทั้งหมด: {student_df.isnull().sum().sum()} ค่า")
print(f"- อายุผิดปกติ: {student_df[student_df['อายุ'] > 100]['อายุ'].values if any(student_df['อายุ'] > 100) else 'ไม่มี'}")
print(f"- GPA ผิดปกติ: {student_df[(student_df['GPA'] < 0) | (student_df['GPA'] > 4)]['GPA'].values if any((student_df['GPA'] < 0) | (student_df['GPA'] > 4)) else 'ไม่มี'}")
print(f"- รูปแบบการเขียนคณะ: {student_df['คณะ'].nunique()} แบบ")
print(f"- รูปแบบการเขียนเพศ: {student_df['เพศ'].nunique()} แบบ")

==================================================
🎯 ข้อมูลหลัก (Master Dataset) ที่จะใช้ตลอดบทเรียน
==================================================
   รหัสนักศึกษา      ชื่อ   อายุ     เพศ             คณะ   GPA  ส่วนสูง_cm  \
0         64001     สมชาย   20.0     ชาย     วิทยาศาสตร์  3.21       170.0
1         64002    สมหญิง   21.0    หญิง           วิทย์  3.45       165.0
2         64003      None    NaN    Male         Science  3.67       175.0
3         64004  สมศักดิ์   22.0       ช  คณะวิทยาศาสตร์ -1.00       168.0
4         64005      สมใจ   19.0       ญ           วิศวะ  3.89       160.0
5         64006     กานต์  150.0     ชาย     Engineering  3.12       172.0
6         64007     กิตติ   21.0    หญิง        วิศวกรรม  4.50       158.0
7         64008      จิรา   20.0       F      ศิลปศาสตร์  2.98       180.0
8         64009    ชนาธิป   23.0       M            Arts  3.34       163.0
9         64010      ดารา   21.0    หญิง           ศิลป์  3.56       167.0
10        64011      ธีระ    NaN    None            None  3.78         NaN
11        64012       นภา   22.0     ชาย           วิทย์   NaN       171.0
12        64013     บุญมี   20.0    หญิง           วิศวฯ  3.23       169.0
13        64014     ปรีชา   21.0     ชาย    Liberal Arts  3.45       164.0
14        64015     พิมพ์   22.0  Female             Sci  3.67       162.0
15        64016      ภูมิ   19.0       ช     วิทยาศาสตร์  3.89       173.0
16        64017      มานี   20.0       ญ  วิศวกรรมศาสตร์  3.01       166.0
17        64018      ยุพา   21.0    หญิง            None  3.23       161.0
18        64019     รัตนา    NaN     ชาย      ศิลปศาสตร์   NaN       174.0
19        64020     ลัดดา   22.0    None         Science  3.45       168.0

    น้ำหนัก_kg  ชั่วโมงเรียน_ต่อสัปดาห์ วันที่ลงทะเบียน
0         65.0                     15.0      2024-01-23
1         58.0                     20.0      2024-02-05
2          NaN                     25.0      2024-01-13
3         70.0                     10.0      2023-12-30
4         52.0                     30.0      2024-01-27
5         75.0                     12.0      2023-12-23
6         48.0                     35.0      2024-01-05
7         82.0                     18.0      2024-01-23
8         55.0                     22.0      2024-02-11
9         60.0                     28.0      2024-01-03
10        68.0                      NaN      2024-01-07
11         NaN                     16.0      2023-12-26
12        72.0                     24.0      2023-12-26
13        54.0                     19.0      2024-01-08
14        56.0                     26.0      2024-02-06
15        78.0                     14.0      2024-01-20
16        62.0                     21.0      2024-01-24
17        50.0                     27.0      2024-01-08
18        76.0                      NaN      2023-12-18
19        64.0                     23.0      2024-01-06

📊 สรุปปัญหาที่พบในข้อมูล:
- ค่าหายทั้งหมด: 15 ค่า
- อายุผิดปกติ: [150.]
- GPA ผิดปกติ: [-1.   4.5]
- รูปแบบการเขียนคณะ: 14 แบบ
- รูปแบบการเขียนเพศ: 8 แบบ

แสดงข้อมูลหลัก แสดง DataFrame student_df
สรุปปัญหาที่พบในข้อมูล
ค่าหาย: แสดงจำนวนค่าที่หายไปทั้งหมด
อายุผิดปกติ: แสดงข้อมูลอายุที่มากกว่า 100
GPA ผิดปกติ: แสดงข้อมูล GPA ที่น้อยกว่า 0 หรือมากกว่า 4
รูปแบบการเขียนคณะ: แสดงจำนวนรูปแบบที่แตกต่างกันของการเขียนชื่อคณะ
รูปแบบการเขียนเพศ: แสดงจำนวนรูปแบบที่แตกต่างกันของการเขียนชื่อเพศ

In [62]:
student_df

,รหัสนักศึกษา,ชื่อ,อายุ,เพศ,คณะ,GPA,ส่วนสูง_cm,น้ำหนัก_kg,ชั่วโมงเรียน_ต่อสัปดาห์,วันที่ลงทะเบียน
0,64001,สมชาย,20.0,ชาย,วิทยาศาสตร์,3.21,170.0,65.0,15.0,2024-01-23
1,64002,สมหญิง,21.0,หญิง,วิทย์,3.45,165.0,58.0,20.0,2024-02-05
2,64003,None,NaN,Male,Science,3.67,175.0,NaN,25.0,2024-01-13
3,64004,สมศักดิ์,22.0,ช,คณะวิทยาศาสตร์,-1.00,168.0,70.0,10.0,2023-12-30
4,64005,สมใจ,19.0,ญ,วิศวะ,3.89,160.0,52.0,30.0,2024-01-27
5,64006,กานต์,150.0,ชาย,Engineering,3.12,172.0,75.0,12.0,2023-12-23
6,64007,กิตติ,21.0,หญิง,วิศวกรรม,4.50,158.0,48.0,35.0,2024-01-05
7,64008,จิรา,20.0,F,ศิลปศาสตร์,2.98,180.0,82.0,18.0,2024-01-23
8,64009,ชนาธิป,23.0,M,Arts,3.34,163.0,55.0,22.0,2024-02-11
9,64010,ดารา,21.0,หญิง,ศิลป์,3.56,167.0,60.0,28.0,2024-01-03
10,64011,ธีระ,NaN,None,None,3.78,NaN,68.0,NaN,2024-01-07
11,64012,นภา,22.0,ชาย,วิทย์,NaN,171.0,NaN,16.0,2023-12-26
12,64013,บุญมี,20.0,หญิง,วิศวฯ,3.23,169.0,72.0,24.0,2023-12-26
13,64014,ปรีชา,21.0,ชาย,Liberal Arts,3.45,164.0,54.0,19.0,2024-01-08
14,64015,พิมพ์,22.0,Female,Sci,3.67,162.0,56.0,26.0,2024-02-06
15,64016,ภูมิ,19.0,ช,วิทยาศาสตร์,3.89,173.0,78.0,14.0,2024-01-20
16,64017,มานี,20.0,ญ,วิศวกรรมศาสตร์,3.01,166.0,62.0,21.0,2024-01-24
17,64018,ยุพา,21.0,หญิง,None,3.23,161.0,50.0,27.0,2024-01-08
18,64019,รัตนา,NaN,ชาย,ศิลปศาสตร์,NaN,174.0,76.0,NaN,2023-12-18
19,64020,ลัดดา,22.0,None,Science,3.45,168.0,64.0,23.0,2024-01-06

In [63]:
student_df.isnull().sum().sum()

np.int64(15)

คำสั่งนี้จะทำให้เเสดงเป็นจำนวนค่าที่หายไปทั้งหมด

In [64]:
student_df['คณะ'].nunique()

14

จะทำการนับจำนวนค่าที่ไม่ซ้ำกันในคอลัมน์ 'คณะ'

In [65]:
print("="*50)
print("📋 ข้อมูลทั่วไปของ Dataset")
print("="*50)
student_df.info()

print("\n" + "="*50)
print("📊 สถิติเชิงพรรณนา")
print("="*50)
print(student_df.describe())

# ตรวจสอบค่าหายในแต่ละคอลัมน์
missing_counts = student_df.isnull().sum()
print("\n❌ ค่าหายในแต่ละคอลัมน์:")
for col, count in missing_counts[missing_counts > 0].items():
    percentage = (count / len(student_df)) * 100
    print(f"   - {col}: {count} ค่า ({percentage:.1f}%)")

==================================================
📋 ข้อมูลทั่วไปของ Dataset
==================================================
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 10 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   รหัสนักศึกษา             20 non-null     object
 1   ชื่อ                     19 non-null     object
 2   อายุ                     17 non-null     float64
 3   เพศ                      18 non-null     object
 4   คณะ                      18 non-null     object
 5   GPA                      18 non-null     float64
 6   ส่วนสูง_cm               19 non-null     float64
 7   น้ำหนัก_kg               18 non-null     float64
 8   ชั่วโมงเรียน_ต่อสัปดาห์  18 non-null     float64
 9   วันที่ลงทะเบียน          20 non-null     datetime64[ns]
dtypes: datetime64[ns](1), float64(5), object(4)
memory usage: 1.7+ KB

==================================================
📊 สถิติเชิงพรรณนา
==================================================
             อายุ        GPA  ส่วนสูง_cm  น้ำหนัก_kg  ชั่วโมงเรียน_ต่อสัปดาห์  \
count   17.000000  18.000000   19.000000   18.000000                18.000000
mean    28.470588   3.246111  167.684211   63.611111                21.388889
min     19.000000  -1.000000  158.000000   48.000000                10.000000
25%     20.000000   3.215000  163.500000   55.250000                16.500000
50%     21.000000   3.450000  168.000000   63.000000                21.500000
75%     22.000000   3.670000  171.500000   71.500000                25.750000
max    150.000000   4.500000  180.000000   82.000000                35.000000
std     31.337114   1.123326    5.706260   10.279270                 6.598920

           วันที่ลงทะเบียน
count                   20
mean   2024-01-12 12:00:00
min    2023-12-18 00:00:00
25%    2024-01-02 00:00:00
50%    2024-01-08 00:00:00
75%    2024-01-23 06:00:00
max    2024-02-11 00:00:00
std                    NaN

❌ ค่าหายในแต่ละคอลัมน์:
   - ชื่อ: 1 ค่า (5.0%)
   - อายุ: 3 ค่า (15.0%)
   - เพศ: 2 ค่า (10.0%)
   - คณะ: 2 ค่า (10.0%)
   - GPA: 2 ค่า (10.0%)
   - ส่วนสูง_cm: 1 ค่า (5.0%)
   - น้ำหนัก_kg: 2 ค่า (10.0%)
   - ชั่วโมงเรียน_ต่อสัปดาห์: 2 ค่า (10.0%)

ผลลัพธ์ที่ได้

ข้อมูลทั่วไป:ข้อมูลเชิงลึกเกี่ยวกับ DataFrame

สถิติ:สถิติที่ช่วยให้เข้าใจลักษณะทั่วไปของข้อมูล

ค่าหายในแต่ละคอลัมน์:แสดงค่าที่หายไปในแต่ละคอลัมน์พร้อมเปอร์เซ็นต์

In [70]:
df_clean = df.dropna()

การทำงานของบรรทัดนี้

dropna(): ลบแถวที่มีค่า NaN (ค่าหาย) ในทุกคอลัมน์

df_clean: ตัวแปรใหม่ที่เก็บ DataFrame หลังจากลบแถวที่มีค่าหายแล้ว

In [69]:
df_clean

,รหัสนักศึกษา,ชื่อ,อายุ,เพศ,คณะ,GPA,ส่วนสูง_cm,น้ำหนัก_kg,ชั่วโมงเรียน_ต่อสัปดาห์,วันที่ลงทะเบียน
0,64001,สมชาย,20.0,ชาย,วิทยาศาสตร์,3.21,170.0,65.0,15.0,2024-02-06
1,64002,สมหญิง,21.0,หญิง,วิทย์,3.45,165.0,58.0,20.0,2023-12-17
3,64004,สมศักดิ์,22.0,ช,คณะวิทยาศาสตร์,-1.00,168.0,70.0,10.0,2024-01-28
4,64005,สมใจ,19.0,ญ,วิศวะ,3.89,160.0,52.0,30.0,2024-01-14
5,64006,กานต์,150.0,ชาย,Engineering,3.12,172.0,75.0,12.0,2024-01-22
6,64007,กิตติ,21.0,หญิง,วิศวกรรม,4.50,158.0,48.0,35.0,2023-12-17
7,64008,จิรา,20.0,F,ศิลปศาสตร์,2.98,180.0,82.0,18.0,2024-02-13
8,64009,ชนาธิป,23.0,M,Arts,3.34,163.0,55.0,22.0,2024-01-05
9,64010,ดารา,21.0,หญิง,ศิลป์,3.56,167.0,60.0,28.0,2024-01-17
12,64013,บุญมี,20.0,หญิง,วิศวฯ,3.23,169.0,72.0,24.0,2024-01-06
13,64014,ปรีชา,21.0,ชาย,Liberal Arts,3.45,164.0,54.0,19.0,2024-01-28
14,64015,พิมพ์,22.0,Female,Sci,3.67,162.0,56.0,26.0,2024-01-09
15,64016,ภูมิ,19.0,ช,วิทยาศาสตร์,3.89,173.0,78.0,14.0,2024-02-02
16,64017,มานี,20.0,ญ,วิศวกรรมศาสตร์,3.01,166.0,62.0,21.0,2024-01-11

In [71]:
df

,รหัสนักศึกษา,ชื่อ,อายุ,เพศ,คณะ,GPA,ส่วนสูง_cm,น้ำหนัก_kg,ชั่วโมงเรียน_ต่อสัปดาห์,วันที่ลงทะเบียน
0,64001,สมชาย,20.0,ชาย,วิทยาศาสตร์,3.21,170.0,65.0,15.0,2024-02-06
1,64002,สมหญิง,21.0,หญิง,วิทย์,3.45,165.0,58.0,20.0,2023-12-17
2,64003,NaN,NaN,Male,Science,3.67,175.0,NaN,25.0,2024-01-08
3,64004,สมศักดิ์,22.0,ช,คณะวิทยาศาสตร์,-1.00,168.0,70.0,10.0,2024-01-28
4,64005,สมใจ,19.0,ญ,วิศวะ,3.89,160.0,52.0,30.0,2024-01-14
5,64006,กานต์,150.0,ชาย,Engineering,3.12,172.0,75.0,12.0,2024-01-22
6,64007,กิตติ,21.0,หญิง,วิศวกรรม,4.50,158.0,48.0,35.0,2023-12-17
7,64008,จิรา,20.0,F,ศิลปศาสตร์,2.98,180.0,82.0,18.0,2024-02-13
8,64009,ชนาธิป,23.0,M,Arts,3.34,163.0,55.0,22.0,2024-01-05
9,64010,ดารา,21.0,หญิง,ศิลป์,3.56,167.0,60.0,28.0,2024-01-17
10,64011,ธีระ,NaN,NaN,NaN,3.78,NaN,68.0,NaN,2023-12-27
11,64012,นภา,22.0,ชาย,วิทย์,NaN,171.0,NaN,16.0,2024-02-11
12,64013,บุญมี,20.0,หญิง,วิศวฯ,3.23,169.0,72.0,24.0,2024-01-06
13,64014,ปรีชา,21.0,ชาย,Liberal Arts,3.45,164.0,54.0,19.0,2024-01-28
14,64015,พิมพ์,22.0,Female,Sci,3.67,162.0,56.0,26.0,2024-01-09
15,64016,ภูมิ,19.0,ช,วิทยาศาสตร์,3.89,173.0,78.0,14.0,2024-02-02
16,64017,มานี,20.0,ญ,วิศวกรรมศาสตร์,3.01,166.0,62.0,21.0,2024-01-11
17,64018,ยุพา,21.0,หญิง,NaN,3.23,161.0,50.0,27.0,2024-02-12
18,64019,รัตนา,NaN,ชาย,ศิลปศาสตร์,NaN,174.0,76.0,NaN,2024-01-26
19,64020,ลัดดา,22.0,NaN,Science,3.45,168.0,64.0,23.0,2024-01-12

In [72]:
print("ก่อนเติมค่า")
print(df)

ก่อนเติมค่า
    รหัสนักศึกษา      ชื่อ   อายุ     เพศ             คณะ   GPA  ส่วนสูง_cm  \
0          64001     สมชาย   20.0     ชาย     วิทยาศาสตร์  3.21       170.0
1          64002    สมหญิง   21.0    หญิง           วิทย์  3.45       165.0
2          64003       NaN    NaN    Male         Science  3.67       175.0
3          64004  สมศักดิ์   22.0       ช  คณะวิทยาศาสตร์ -1.00       168.0
4          64005      สมใจ   19.0       ญ           วิศวะ  3.89       160.0
5          64006     กานต์  150.0     ชาย     Engineering  3.12       172.0
6          64007     กิตติ   21.0    หญิง        วิศวกรรม  4.50       158.0
7          64008      จิรา   20.0       F      ศิลปศาสตร์  2.98       180.0
8          64009    ชนาธิป   23.0       M            Arts  3.34       163.0
9          64010      ดารา   21.0    หญิง           ศิลป์  3.56       167.0
10         64011      ธีระ    NaN     NaN             NaN  3.78         NaN
11         64012       นภา   22.0     ชาย           วิทย์   NaN       171.0
12         64013     บุญมี   20.0    หญิง           วิศวฯ  3.23       169.0
13         64014     ปรีชา   21.0     ชาย    Liberal Arts  3.45       164.0
14         64015     พิมพ์   22.0  Female             Sci  3.67       162.0
15         64016      ภูมิ   19.0       ช     วิทยาศาสตร์  3.89       173.0
16         64017      มานี   20.0       ญ  วิศวกรรมศาสตร์  3.01       166.0
17         64018      ยุพา   21.0    หญิง             NaN  3.23       161.0
18         64019     รัตนา    NaN     ชาย      ศิลปศาสตร์   NaN       174.0
19         64020     ลัดดา   22.0     NaN         Science  3.45       168.0

    น้ำหนัก_kg  ชั่วโมงเรียน_ต่อสัปดาห์ วันที่ลงทะเบียน
0         65.0                     15.0      2024-02-06
1         58.0                     20.0      2023-12-17
2          NaN                     25.0      2024-01-08
3         70.0                     10.0      2024-01-28
4         52.0                     30.0      2024-01-14
5         75.0                     12.0      2024-01-22
6         48.0                     35.0      2023-12-17
7         82.0                     18.0      2024-02-13
8         55.0                     22.0      2024-01-05
9         60.0                     28.0      2024-01-17
10        68.0                      NaN      2023-12-27
11         NaN                     16.0      2024-02-11
12        72.0                     24.0      2024-01-06
13        54.0                     19.0      2024-01-28
14        56.0                     26.0      2024-01-09
15        78.0                     14.0      2024-02-02
16        62.0                     21.0      2024-01-11
17        50.0                     27.0      2024-02-12
18        76.0                      NaN      2024-01-26
19        64.0                     23.0      2024-01-12

In [74]:
mean_age = df['อายุ'].mean()

จะเป็นค่าเฉลี่ยของอายุในคอลัมน์ 'อายุ' โดยการละเว้นค่าที่เป็น NaN

In [75]:
mean_age

np.float64(28.470588235294116)

In [80]:
# เติมค่าหายในคอลัมน์ 'อายุ' ด้วยค่าเฉลี่ย
mean_age = df['อายุ'].mean()
df['อายุ'] = df['อายุ'].fillna(mean_age)

# เติมค่าหายในคอลัมน์ 'GPA' ด้วยค่าเฉลี่ย
mean_gpa = df['GPA'].mean()
df['GPA'] = df['GPA'].fillna(mean_gpa)

จะทำการเติมค่าหาย (NaN) ในคอลัมน์ 'อายุ'เเละ 'GPA' ด้วยค่าเฉลี่ยที่คำนวณได้จาก mean_age เเละ mean_gpa

In [108]:

print(f"\nค่าเฉลี่ยอายุ (รวมค่าผิดปกติ) - {df['อายุ'].mean():.2f}")

ค่าเฉลี่ยอายุ (รวมค่าผิดปกติ) - 22.39

In [110]:
Q1 = df['อายุ'].quantile(0.25)
Q3 = df['อายุ'].quantile(0.75)

Q1 คือค่าที่แสดงตำแหน่ง 25% ของข้อมูล

Q3 คือค่าที่แสดงตำแหน่ง 75% ของข้อมูล

การใช้ IQR จะช่วยตรวจจับค่า outlier ได้ โดยการกำหนดค่าที่อยู่นอกช่วง Q1 - 1.5 * IQR ถึง Q3 + 1.5 * IQR ว่าเป็น outliers

In [111]:
Q1,Q3

(np.float64(20.0), np.float64(22.25))

In [112]:
IQR = Q3 - Q1

In [113]:
IQR

np.float64(2.25)

In [115]:
lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR

In [116]:
df_no_outliers = df[(df['อายุ'] >= lower_bound) & (df['อายุ'] <= upper_bound)]

คำสั่งนี้ใช้ IQR เพื่อตรวจจับค่า outliers ในคอลัมน์ อายุ

จะสร้าง DataFrame ใหม่ df_no_outliers ที่กรองข้อมูลที่ไม่เป็น outliers ออกไป

In [ ]:
df_no_outliers = df[(df['อายุ'] >= lower_bound) & (df['อายุ'] <= upper_bound)]

ใช้ในการตรวจจับ outliers โดยค่าที่น้อยกว่าหรือมากกว่าค่านี้ถือเป็น outliers

In [118]:
df_no_outliers

,รหัสนักศึกษา,ชื่อ,อายุ,เพศ,คณะ,GPA,ส่วนสูง_cm,น้ำหนัก_kg,ชั่วโมงเรียน_ต่อสัปดาห์,วันที่ลงทะเบียน
0,64001,สมชาย,20.0,ชาย,วิทยาศาสตร์,3.210000,170.0,65.000000,15.0,2024-02-06
1,64002,สมหญิง,21.0,หญิง,วิทยาศาสตร์,3.450000,165.0,58.000000,20.0,2023-12-17
3,64004,สมศักดิ์,22.0,ชาย,วิทยาศาสตร์,3.469591,168.0,70.000000,10.0,2024-01-28
4,64005,สมใจ,19.0,หญิง,วิศวกรรมศาสตร์,3.890000,160.0,52.000000,30.0,2024-01-14
6,64007,กิตติ,21.0,หญิง,วิศวกรรมศาสตร์,4.500000,158.0,48.000000,35.0,2023-12-17
7,64008,จิรา,20.0,หญิง,ศิลปศาสตร์,2.980000,180.0,82.000000,18.0,2024-02-13
8,64009,ชนาธิป,23.0,ชาย,ศิลปศาสตร์,3.340000,163.0,55.000000,22.0,2024-01-05
9,64010,ดารา,21.0,หญิง,ศิลปศาสตร์,3.560000,167.0,60.000000,28.0,2024-01-17
11,64012,นภา,22.0,ชาย,วิทยาศาสตร์,3.246111,171.0,63.611111,16.0,2024-02-11
12,64013,บุญมี,20.0,หญิง,วิศวกรรมศาสตร์,3.230000,169.0,72.000000,24.0,2024-01-06
13,64014,ปรีชา,21.0,ชาย,ศิลปศาสตร์,3.450000,164.0,54.000000,19.0,2024-01-28
14,64015,พิมพ์,22.0,หญิง,วิทยาศาสตร์,3.670000,162.0,56.000000,26.0,2024-01-09
15,64016,ภูมิ,19.0,ชาย,วิทยาศาสตร์,3.890000,173.0,78.000000,14.0,2024-02-02
16,64017,มานี,20.0,หญิง,วิศวกรรมศาสตร์,3.010000,166.0,62.000000,21.0,2024-01-11
17,64018,ยุพา,21.0,หญิง,วิทยาศาสตร์,3.230000,161.0,50.000000,27.0,2024-02-12
19,64020,ลัดดา,22.0,ชาย,วิทยาศาสตร์,3.450000,168.0,64.000000,23.0,2024-01-12

df_no_outliers คือ DataFrame ที่ไม่มี outliers หลังจากกรองแถวที่มีค่าผิดปกติ

In [119]:
df['อายุ'] >= lower_bound

0     True
1     True
2     True
3     True
4     True
5     True
6     True
7     True
8     True
9     True
10    True
11    True
12    True
13    True
14    True
15    True
16    True
17    True
18    True
19    True
Name: อายุ, dtype: bool

คำสั่ง df['อายุ'] >= lower_bound จะเปรียบเทียบแต่ละค่าในคอลัมน์ อายุ กับ lower_bound และแสดงผลเป็น True หรือ False

In [120]:
df['อายุ'] <= upper_bound

0      True
1      True
2     False
3      True
4      True
5     False
6      True
7      True
8      True
9      True
10    False
11     True
12     True
13     True
14     True
15     True
16     True
17     True
18    False
19     True
Name: อายุ, dtype: bool

คำสั่ง df['อายุ'] <= upper_bound จะตรวจสอบแต่ละค่าในคอลัมน์ อายุ ว่าน้อยกว่าหรือเท่ากับ upper_bound

สามารถใช้ในการกรองข้อมูลหรือคำนวณข้อมูลที่ต้องการ โดยแสดงผลลัพธ์เป็น True หรือ False

In [83]:
df

,รหัสนักศึกษา,ชื่อ,อายุ,เพศ,คณะ,GPA,ส่วนสูง_cm,น้ำหนัก_kg,ชั่วโมงเรียน_ต่อสัปดาห์,วันที่ลงทะเบียน
0,64001,สมชาย,20.000000,ชาย,วิทยาศาสตร์,3.210000,170.0,65.0,15.0,2024-02-06
1,64002,สมหญิง,21.000000,หญิง,วิทย์,3.450000,165.0,58.0,20.0,2023-12-17
2,64003,NaN,28.470588,Male,Science,3.670000,175.0,NaN,25.0,2024-01-08
3,64004,สมศักดิ์,22.000000,ช,คณะวิทยาศาสตร์,-1.000000,168.0,70.0,10.0,2024-01-28
4,64005,สมใจ,19.000000,ญ,วิศวะ,3.890000,160.0,52.0,30.0,2024-01-14
5,64006,กานต์,28.470588,ชาย,Engineering,3.120000,172.0,75.0,12.0,2024-01-22
6,64007,กิตติ,21.000000,หญิง,วิศวกรรม,4.500000,158.0,48.0,35.0,2023-12-17
7,64008,จิรา,20.000000,F,ศิลปศาสตร์,2.980000,180.0,82.0,18.0,2024-02-13
8,64009,ชนาธิป,23.000000,M,Arts,3.340000,163.0,55.0,22.0,2024-01-05
9,64010,ดารา,21.000000,หญิง,ศิลป์,3.560000,167.0,60.0,28.0,2024-01-17
10,64011,ธีระ,28.470588,NaN,NaN,3.780000,NaN,68.0,NaN,2023-12-27
11,64012,นภา,22.000000,ชาย,วิทย์,3.246111,171.0,NaN,16.0,2024-02-11
12,64013,บุญมี,20.000000,หญิง,วิศวฯ,3.230000,169.0,72.0,24.0,2024-01-06
13,64014,ปรีชา,21.000000,ชาย,Liberal Arts,3.450000,164.0,54.0,19.0,2024-01-28
14,64015,พิมพ์,22.000000,Female,Sci,3.670000,162.0,56.0,26.0,2024-01-09
15,64016,ภูมิ,19.000000,ช,วิทยาศาสตร์,3.890000,173.0,78.0,14.0,2024-02-02
16,64017,มานี,20.000000,ญ,วิศวกรรมศาสตร์,3.010000,166.0,62.0,21.0,2024-01-11
17,64018,ยุพา,21.000000,หญิง,NaN,3.230000,161.0,50.0,27.0,2024-02-12
18,64019,รัตนา,28.470588,ชาย,ศิลปศาสตร์,3.246111,174.0,76.0,NaN,2024-01-26
19,64020,ลัดดา,22.000000,NaN,Science,3.450000,168.0,64.0,23.0,2024-01-12

In [84]:
df['ชื่อ'] = df['ชื่อ'].fillna('ไม่ระบุ')

คำสั่งนี้จะทำการแทนที่ค่าที่เป็น NaN ในคอลัมน์ 'ชื่อ' ด้วยข้อความ "ไม่ระบุ"

In [85]:
df

,รหัสนักศึกษา,ชื่อ,อายุ,เพศ,คณะ,GPA,ส่วนสูง_cm,น้ำหนัก_kg,ชั่วโมงเรียน_ต่อสัปดาห์,วันที่ลงทะเบียน
0,64001,สมชาย,20.000000,ชาย,วิทยาศาสตร์,3.210000,170.0,65.0,15.0,2024-02-06
1,64002,สมหญิง,21.000000,หญิง,วิทย์,3.450000,165.0,58.0,20.0,2023-12-17
2,64003,ไม่ระบุ,28.470588,Male,Science,3.670000,175.0,NaN,25.0,2024-01-08
3,64004,สมศักดิ์,22.000000,ช,คณะวิทยาศาสตร์,-1.000000,168.0,70.0,10.0,2024-01-28
4,64005,สมใจ,19.000000,ญ,วิศวะ,3.890000,160.0,52.0,30.0,2024-01-14
5,64006,กานต์,28.470588,ชาย,Engineering,3.120000,172.0,75.0,12.0,2024-01-22
6,64007,กิตติ,21.000000,หญิง,วิศวกรรม,4.500000,158.0,48.0,35.0,2023-12-17
7,64008,จิรา,20.000000,F,ศิลปศาสตร์,2.980000,180.0,82.0,18.0,2024-02-13
8,64009,ชนาธิป,23.000000,M,Arts,3.340000,163.0,55.0,22.0,2024-01-05
9,64010,ดารา,21.000000,หญิง,ศิลป์,3.560000,167.0,60.0,28.0,2024-01-17
10,64011,ธีระ,28.470588,NaN,NaN,3.780000,NaN,68.0,NaN,2023-12-27
11,64012,นภา,22.000000,ชาย,วิทย์,3.246111,171.0,NaN,16.0,2024-02-11
12,64013,บุญมี,20.000000,หญิง,วิศวฯ,3.230000,169.0,72.0,24.0,2024-01-06
13,64014,ปรีชา,21.000000,ชาย,Liberal Arts,3.450000,164.0,54.0,19.0,2024-01-28
14,64015,พิมพ์,22.000000,Female,Sci,3.670000,162.0,56.0,26.0,2024-01-09
15,64016,ภูมิ,19.000000,ช,วิทยาศาสตร์,3.890000,173.0,78.0,14.0,2024-02-02
16,64017,มานี,20.000000,ญ,วิศวกรรมศาสตร์,3.010000,166.0,62.0,21.0,2024-01-11
17,64018,ยุพา,21.000000,หญิง,NaN,3.230000,161.0,50.0,27.0,2024-02-12
18,64019,รัตนา,28.470588,ชาย,ศิลปศาสตร์,3.246111,174.0,76.0,NaN,2024-01-26
19,64020,ลัดดา,22.000000,NaN,Science,3.450000,168.0,64.0,23.0,2024-01-12

In [87]:
# เติมค่า NaN ในคอลัมน์ 'เพศ' ด้วยค่าที่พบมากที่สุด (mode)
mode_gender = df['เพศ'].mode()[0]
df['เพศ'] = df['เพศ'].fillna(mode_gender)
df['เพศ'] = df['เพศ'].replace({'M': 'ชาย', 'F': 'หญิง', 'ช': 'ชาย', 'ญ': 'หญิง'})
df['เพศ'] = df['เพศ'].replace({'Male': 'ชาย', 'Female': 'หญิง'})


เติมค่า NaN ในคอลัมน์ 'เพศ' ด้วยค่า mode (ค่าที่พบมากที่สุด) เพื่อให้ข้อมูลที่หายไปมีความสมเหตุสมผลตามข้อมูลที่มีอยู่

แทนที่ค่าผิดปกติ เช่น 'M' → 'ชาย', 'F' → 'หญิง', 'ช' → 'ชาย', 'ญ' → 'หญิง' เพื่อให้ข้อมูลมีรูปแบบที่ถูกต้อง

แทนที่ค่าภาษาอังกฤษ เช่น 'Male' → 'ชาย' และ 'Female' → 'หญิง' เพื่อให้ข้อมูลทั้งหมดอยู่ในรูปแบบเดียวกัน

In [88]:
df

,รหัสนักศึกษา,ชื่อ,อายุ,เพศ,คณะ,GPA,ส่วนสูง_cm,น้ำหนัก_kg,ชั่วโมงเรียน_ต่อสัปดาห์,วันที่ลงทะเบียน
0,64001,สมชาย,20.000000,ชาย,วิทยาศาสตร์,3.210000,170.0,65.0,15.0,2024-02-06
1,64002,สมหญิง,21.000000,หญิง,วิทย์,3.450000,165.0,58.0,20.0,2023-12-17
2,64003,ไม่ระบุ,28.470588,ชาย,Science,3.670000,175.0,NaN,25.0,2024-01-08
3,64004,สมศักดิ์,22.000000,ชาย,คณะวิทยาศาสตร์,-1.000000,168.0,70.0,10.0,2024-01-28
4,64005,สมใจ,19.000000,หญิง,วิศวะ,3.890000,160.0,52.0,30.0,2024-01-14
5,64006,กานต์,28.470588,ชาย,Engineering,3.120000,172.0,75.0,12.0,2024-01-22
6,64007,กิตติ,21.000000,หญิง,วิศวกรรม,4.500000,158.0,48.0,35.0,2023-12-17
7,64008,จิรา,20.000000,หญิง,ศิลปศาสตร์,2.980000,180.0,82.0,18.0,2024-02-13
8,64009,ชนาธิป,23.000000,ชาย,Arts,3.340000,163.0,55.0,22.0,2024-01-05
9,64010,ดารา,21.000000,หญิง,ศิลป์,3.560000,167.0,60.0,28.0,2024-01-17
10,64011,ธีระ,28.470588,ชาย,NaN,3.780000,NaN,68.0,NaN,2023-12-27
11,64012,นภา,22.000000,ชาย,วิทย์,3.246111,171.0,NaN,16.0,2024-02-11
12,64013,บุญมี,20.000000,หญิง,วิศวฯ,3.230000,169.0,72.0,24.0,2024-01-06
13,64014,ปรีชา,21.000000,ชาย,Liberal Arts,3.450000,164.0,54.0,19.0,2024-01-28
14,64015,พิมพ์,22.000000,หญิง,Sci,3.670000,162.0,56.0,26.0,2024-01-09
15,64016,ภูมิ,19.000000,ชาย,วิทยาศาสตร์,3.890000,173.0,78.0,14.0,2024-02-02
16,64017,มานี,20.000000,หญิง,วิศวกรรมศาสตร์,3.010000,166.0,62.0,21.0,2024-01-11
17,64018,ยุพา,21.000000,หญิง,NaN,3.230000,161.0,50.0,27.0,2024-02-12
18,64019,รัตนา,28.470588,ชาย,ศิลปศาสตร์,3.246111,174.0,76.0,NaN,2024-01-26
19,64020,ลัดดา,22.000000,ชาย,Science,3.450000,168.0,64.0,23.0,2024-01-12

In [89]:
# เติมค่าที่หายไปในคอลัมน์ 'คณะ' ด้วยค่า mode (คณะที่พบมากที่สุด)
mode_faculty = df['คณะ'].mode()[0]
df['คณะ'] = df['คณะ'].fillna(mode_faculty)

เติมค่าที่หายไปในคอลัมน์ 'คณะ' ด้วยค่า mode (คณะที่พบมากที่สุด)

In [131]:

faculty_mapping = {
    'วิทย์': 'วิทยาศาสตร์',
    'คณะวิทยาศาสตร์': 'วิทยาศาสตร์',
    'วิศวะ': 'วิศวกรรม',
    'วิศวฯ': 'วิศวกรรม',
    'วิศวกรรม': 'วิศวกรรมศาสตร์',
    'Science': 'วิทยาศาสตร์',
    'Engineering': 'วิศวกรรมศาสตร์',
    'ศิลป์': 'ศิลปศาสตร์',
    'Arts': 'ศิลปศาสตร์',
    'Sci': 'วิทยาศาสตร์',
    'Liberal Arts': 'ศิลปศาสตร์'
}

แทนที่ค่าผิดปกติในคอลัมน์ 'คณะ' เช่น คณะที่เขียนไม่เหมือนกัน

In [133]:
faculty_mapping

{'วิทย์': 'วิทยาศาสตร์',
 'คณะวิทยาศาสตร์': 'วิทยาศาสตร์',
 'วิศวะ': 'วิศวกรรม',
 'วิศวฯ': 'วิศวกรรม',
 'วิศวกรรม': 'วิศวกรรมศาสตร์',
 'Science': 'วิทยาศาสตร์',
 'Engineering': 'วิศวกรรมศาสตร์',
 'ศิลป์': 'ศิลปศาสตร์',
 'Arts': 'ศิลปศาสตร์',
 'Sci': 'วิทยาศาสตร์',
 'Liberal Arts': 'ศิลปศาสตร์'}

In [132]:
df

,รหัสนักศึกษา,ชื่อ,อายุ,เพศ,คณะ,GPA,ส่วนสูง_cm,น้ำหนัก_kg,ชั่วโมงเรียน_ต่อสัปดาห์,วันที่ลงทะเบียน,วันในสัปดาห์
0,64001,สมชาย,20.000000,ชาย,วิทยาศาสตร์,3.210000,170.000000,65.000000,15.000000,2024-02-06,Tuesday
1,64002,สมหญิง,21.000000,หญิง,วิทยาศาสตร์,3.450000,165.000000,58.000000,20.000000,2023-12-17,Sunday
2,64003,ไม่ระบุ,28.470588,ชาย,วิทยาศาสตร์,3.670000,175.000000,63.611111,25.000000,2024-01-08,Monday
3,64004,สมศักดิ์,22.000000,ชาย,วิทยาศาสตร์,3.469591,168.000000,70.000000,10.000000,2024-01-28,Sunday
4,64005,สมใจ,19.000000,หญิง,วิศวกรรมศาสตร์,3.890000,160.000000,52.000000,30.000000,2024-01-14,Sunday
5,64006,กานต์,28.470588,ชาย,วิศวกรรมศาสตร์,3.120000,172.000000,75.000000,12.000000,2024-01-22,Monday
6,64007,กิตติ,21.000000,หญิง,วิศวกรรมศาสตร์,4.500000,158.000000,48.000000,35.000000,2023-12-17,Sunday
7,64008,จิรา,20.000000,หญิง,ศิลปศาสตร์,2.980000,180.000000,82.000000,18.000000,2024-02-13,Tuesday
8,64009,ชนาธิป,23.000000,ชาย,ศิลปศาสตร์,3.340000,163.000000,55.000000,22.000000,2024-01-05,Friday
9,64010,ดารา,21.000000,หญิง,ศิลปศาสตร์,3.560000,167.000000,60.000000,28.000000,2024-01-17,Wednesday
10,64011,ธีระ,28.470588,ชาย,วิทยาศาสตร์,3.780000,167.684211,68.000000,21.388889,2023-12-27,Wednesday
11,64012,นภา,22.000000,ชาย,วิทยาศาสตร์,3.246111,171.000000,63.611111,16.000000,2024-02-11,Sunday
12,64013,บุญมี,20.000000,หญิง,วิศวกรรมศาสตร์,3.230000,169.000000,72.000000,24.000000,2024-01-06,Saturday
13,64014,ปรีชา,21.000000,ชาย,ศิลปศาสตร์,3.450000,164.000000,54.000000,19.000000,2024-01-28,Sunday
14,64015,พิมพ์,22.000000,หญิง,วิทยาศาสตร์,3.670000,162.000000,56.000000,26.000000,2024-01-09,Tuesday
15,64016,ภูมิ,19.000000,ชาย,วิทยาศาสตร์,3.890000,173.000000,78.000000,14.000000,2024-02-02,Friday
16,64017,มานี,20.000000,หญิง,วิศวกรรมศาสตร์,3.010000,166.000000,62.000000,21.000000,2024-01-11,Thursday
17,64018,ยุพา,21.000000,หญิง,วิทยาศาสตร์,3.230000,161.000000,50.000000,27.000000,2024-02-12,Monday
18,64019,รัตนา,28.470588,ชาย,ศิลปศาสตร์,3.246111,174.000000,76.000000,21.388889,2024-01-26,Friday
19,64020,ลัดดา,22.000000,ชาย,วิทยาศาสตร์,3.450000,168.000000,64.000000,23.000000,2024-01-12,Friday

In [97]:

df['GPA'] = df['GPA'].replace(-1, np.nan)


mean_gpa = df['GPA'].mean()
df['GPA'] = df['GPA'].fillna(mean_gpa)

แทนที่ค่า -1 ด้วย NaN เเละ เติมค่าที่หายไป (NaN) ด้วยค่าเฉลี่ยของ GPA

In [98]:
df

,รหัสนักศึกษา,ชื่อ,อายุ,เพศ,คณะ,GPA,ส่วนสูง_cm,น้ำหนัก_kg,ชั่วโมงเรียน_ต่อสัปดาห์,วันที่ลงทะเบียน
0,64001,สมชาย,20.000000,ชาย,วิทยาศาสตร์,3.210000,170.0,65.0,15.0,2024-02-06
1,64002,สมหญิง,21.000000,หญิง,วิทยาศาสตร์,3.450000,165.0,58.0,20.0,2023-12-17
2,64003,ไม่ระบุ,28.470588,ชาย,วิทยาศาสตร์,3.670000,175.0,NaN,25.0,2024-01-08
3,64004,สมศักดิ์,22.000000,ชาย,วิทยาศาสตร์,3.469591,168.0,70.0,10.0,2024-01-28
4,64005,สมใจ,19.000000,หญิง,วิศวกรรมศาสตร์,3.890000,160.0,52.0,30.0,2024-01-14
5,64006,กานต์,28.470588,ชาย,วิศวกรรมศาสตร์,3.120000,172.0,75.0,12.0,2024-01-22
6,64007,กิตติ,21.000000,หญิง,วิศวกรรมศาสตร์,4.500000,158.0,48.0,35.0,2023-12-17
7,64008,จิรา,20.000000,หญิง,ศิลปศาสตร์,2.980000,180.0,82.0,18.0,2024-02-13
8,64009,ชนาธิป,23.000000,ชาย,ศิลปศาสตร์,3.340000,163.0,55.0,22.0,2024-01-05
9,64010,ดารา,21.000000,หญิง,ศิลปศาสตร์,3.560000,167.0,60.0,28.0,2024-01-17
10,64011,ธีระ,28.470588,ชาย,วิทยาศาสตร์,3.780000,NaN,68.0,NaN,2023-12-27
11,64012,นภา,22.000000,ชาย,วิทยาศาสตร์,3.246111,171.0,NaN,16.0,2024-02-11
12,64013,บุญมี,20.000000,หญิง,วิศวกรรมศาสตร์,3.230000,169.0,72.0,24.0,2024-01-06
13,64014,ปรีชา,21.000000,ชาย,ศิลปศาสตร์,3.450000,164.0,54.0,19.0,2024-01-28
14,64015,พิมพ์,22.000000,หญิง,วิทยาศาสตร์,3.670000,162.0,56.0,26.0,2024-01-09
15,64016,ภูมิ,19.000000,ชาย,วิทยาศาสตร์,3.890000,173.0,78.0,14.0,2024-02-02
16,64017,มานี,20.000000,หญิง,วิศวกรรมศาสตร์,3.010000,166.0,62.0,21.0,2024-01-11
17,64018,ยุพา,21.000000,หญิง,วิทยาศาสตร์,3.230000,161.0,50.0,27.0,2024-02-12
18,64019,รัตนา,28.470588,ชาย,ศิลปศาสตร์,3.246111,174.0,76.0,NaN,2024-01-26
19,64020,ลัดดา,22.000000,ชาย,วิทยาศาสตร์,3.450000,168.0,64.0,23.0,2024-01-12

In [99]:

mean_height = df['ส่วนสูง_cm'].mean()


df['ส่วนสูง_cm'] = df['ส่วนสูง_cm'].fillna(mean_height)

คำนวณค่าเฉลี่ยของคอลัมน์ 'ส่วนสูง_cm' เเละ  เติมค่าที่หายไป (NaN) ด้วยค่าเฉลี่ย

In [100]:
df

,รหัสนักศึกษา,ชื่อ,อายุ,เพศ,คณะ,GPA,ส่วนสูง_cm,น้ำหนัก_kg,ชั่วโมงเรียน_ต่อสัปดาห์,วันที่ลงทะเบียน
0,64001,สมชาย,20.000000,ชาย,วิทยาศาสตร์,3.210000,170.000000,65.0,15.0,2024-02-06
1,64002,สมหญิง,21.000000,หญิง,วิทยาศาสตร์,3.450000,165.000000,58.0,20.0,2023-12-17
2,64003,ไม่ระบุ,28.470588,ชาย,วิทยาศาสตร์,3.670000,175.000000,NaN,25.0,2024-01-08
3,64004,สมศักดิ์,22.000000,ชาย,วิทยาศาสตร์,3.469591,168.000000,70.0,10.0,2024-01-28
4,64005,สมใจ,19.000000,หญิง,วิศวกรรมศาสตร์,3.890000,160.000000,52.0,30.0,2024-01-14
5,64006,กานต์,28.470588,ชาย,วิศวกรรมศาสตร์,3.120000,172.000000,75.0,12.0,2024-01-22
6,64007,กิตติ,21.000000,หญิง,วิศวกรรมศาสตร์,4.500000,158.000000,48.0,35.0,2023-12-17
7,64008,จิรา,20.000000,หญิง,ศิลปศาสตร์,2.980000,180.000000,82.0,18.0,2024-02-13
8,64009,ชนาธิป,23.000000,ชาย,ศิลปศาสตร์,3.340000,163.000000,55.0,22.0,2024-01-05
9,64010,ดารา,21.000000,หญิง,ศิลปศาสตร์,3.560000,167.000000,60.0,28.0,2024-01-17
10,64011,ธีระ,28.470588,ชาย,วิทยาศาสตร์,3.780000,167.684211,68.0,NaN,2023-12-27
11,64012,นภา,22.000000,ชาย,วิทยาศาสตร์,3.246111,171.000000,NaN,16.0,2024-02-11
12,64013,บุญมี,20.000000,หญิง,วิศวกรรมศาสตร์,3.230000,169.000000,72.0,24.0,2024-01-06
13,64014,ปรีชา,21.000000,ชาย,ศิลปศาสตร์,3.450000,164.000000,54.0,19.0,2024-01-28
14,64015,พิมพ์,22.000000,หญิง,วิทยาศาสตร์,3.670000,162.000000,56.0,26.0,2024-01-09
15,64016,ภูมิ,19.000000,ชาย,วิทยาศาสตร์,3.890000,173.000000,78.0,14.0,2024-02-02
16,64017,มานี,20.000000,หญิง,วิศวกรรมศาสตร์,3.010000,166.000000,62.0,21.0,2024-01-11
17,64018,ยุพา,21.000000,หญิง,วิทยาศาสตร์,3.230000,161.000000,50.0,27.0,2024-02-12
18,64019,รัตนา,28.470588,ชาย,ศิลปศาสตร์,3.246111,174.000000,76.0,NaN,2024-01-26
19,64020,ลัดดา,22.000000,ชาย,วิทยาศาสตร์,3.450000,168.000000,64.0,23.0,2024-01-12

In [103]:

mean_weight = df['น้ำหนัก_kg'].mean()


df['น้ำหนัก_kg'] = df['น้ำหนัก_kg'].fillna(mean_weight)

คำนวณค่าเฉลี่ยของคอลัมน์ 'น้ำหนัก_kg' เติมค่าที่หายไป (NaN) ด้วยค่าเฉลี่ย

In [102]:
df

,รหัสนักศึกษา,ชื่อ,อายุ,เพศ,คณะ,GPA,ส่วนสูง_cm,น้ำหนัก_kg,ชั่วโมงเรียน_ต่อสัปดาห์,วันที่ลงทะเบียน
0,64001,สมชาย,20.000000,ชาย,วิทยาศาสตร์,3.210000,170.000000,65.000000,15.0,2024-02-06
1,64002,สมหญิง,21.000000,หญิง,วิทยาศาสตร์,3.450000,165.000000,58.000000,20.0,2023-12-17
2,64003,ไม่ระบุ,28.470588,ชาย,วิทยาศาสตร์,3.670000,175.000000,63.611111,25.0,2024-01-08
3,64004,สมศักดิ์,22.000000,ชาย,วิทยาศาสตร์,3.469591,168.000000,70.000000,10.0,2024-01-28
4,64005,สมใจ,19.000000,หญิง,วิศวกรรมศาสตร์,3.890000,160.000000,52.000000,30.0,2024-01-14
5,64006,กานต์,28.470588,ชาย,วิศวกรรมศาสตร์,3.120000,172.000000,75.000000,12.0,2024-01-22
6,64007,กิตติ,21.000000,หญิง,วิศวกรรมศาสตร์,4.500000,158.000000,48.000000,35.0,2023-12-17
7,64008,จิรา,20.000000,หญิง,ศิลปศาสตร์,2.980000,180.000000,82.000000,18.0,2024-02-13
8,64009,ชนาธิป,23.000000,ชาย,ศิลปศาสตร์,3.340000,163.000000,55.000000,22.0,2024-01-05
9,64010,ดารา,21.000000,หญิง,ศิลปศาสตร์,3.560000,167.000000,60.000000,28.0,2024-01-17
10,64011,ธีระ,28.470588,ชาย,วิทยาศาสตร์,3.780000,167.684211,68.000000,NaN,2023-12-27
11,64012,นภา,22.000000,ชาย,วิทยาศาสตร์,3.246111,171.000000,63.611111,16.0,2024-02-11
12,64013,บุญมี,20.000000,หญิง,วิศวกรรมศาสตร์,3.230000,169.000000,72.000000,24.0,2024-01-06
13,64014,ปรีชา,21.000000,ชาย,ศิลปศาสตร์,3.450000,164.000000,54.000000,19.0,2024-01-28
14,64015,พิมพ์,22.000000,หญิง,วิทยาศาสตร์,3.670000,162.000000,56.000000,26.0,2024-01-09
15,64016,ภูมิ,19.000000,ชาย,วิทยาศาสตร์,3.890000,173.000000,78.000000,14.0,2024-02-02
16,64017,มานี,20.000000,หญิง,วิศวกรรมศาสตร์,3.010000,166.000000,62.000000,21.0,2024-01-11
17,64018,ยุพา,21.000000,หญิง,วิทยาศาสตร์,3.230000,161.000000,50.000000,27.0,2024-02-12
18,64019,รัตนา,28.470588,ชาย,ศิลปศาสตร์,3.246111,174.000000,76.000000,NaN,2024-01-26
19,64020,ลัดดา,22.000000,ชาย,วิทยาศาสตร์,3.450000,168.000000,64.000000,23.0,2024-01-12

In [106]:

mean_study_hours = df['ชั่วโมงเรียน_ต่อสัปดาห์'].mean()

df['ชั่วโมงเรียน_ต่อสัปดาห์'] = df['ชั่วโมงเรียน_ต่อสัปดาห์'].fillna(mean_study_hours)

คำนวณค่าเฉลี่ยของคอลัมน์ 'ชั่วโมงเรียน_ต่อสัปดาห์' เติมค่าที่หายไป (NaN) ด้วยค่าเฉลี่ย

In [107]:
df

,รหัสนักศึกษา,ชื่อ,อายุ,เพศ,คณะ,GPA,ส่วนสูง_cm,น้ำหนัก_kg,ชั่วโมงเรียน_ต่อสัปดาห์,วันที่ลงทะเบียน
0,64001,สมชาย,20.000000,ชาย,วิทยาศาสตร์,3.210000,170.000000,65.000000,15.000000,2024-02-06
1,64002,สมหญิง,21.000000,หญิง,วิทยาศาสตร์,3.450000,165.000000,58.000000,20.000000,2023-12-17
2,64003,ไม่ระบุ,28.470588,ชาย,วิทยาศาสตร์,3.670000,175.000000,63.611111,25.000000,2024-01-08
3,64004,สมศักดิ์,22.000000,ชาย,วิทยาศาสตร์,3.469591,168.000000,70.000000,10.000000,2024-01-28
4,64005,สมใจ,19.000000,หญิง,วิศวกรรมศาสตร์,3.890000,160.000000,52.000000,30.000000,2024-01-14
5,64006,กานต์,28.470588,ชาย,วิศวกรรมศาสตร์,3.120000,172.000000,75.000000,12.000000,2024-01-22
6,64007,กิตติ,21.000000,หญิง,วิศวกรรมศาสตร์,4.500000,158.000000,48.000000,35.000000,2023-12-17
7,64008,จิรา,20.000000,หญิง,ศิลปศาสตร์,2.980000,180.000000,82.000000,18.000000,2024-02-13
8,64009,ชนาธิป,23.000000,ชาย,ศิลปศาสตร์,3.340000,163.000000,55.000000,22.000000,2024-01-05
9,64010,ดารา,21.000000,หญิง,ศิลปศาสตร์,3.560000,167.000000,60.000000,28.000000,2024-01-17
10,64011,ธีระ,28.470588,ชาย,วิทยาศาสตร์,3.780000,167.684211,68.000000,21.388889,2023-12-27
11,64012,นภา,22.000000,ชาย,วิทยาศาสตร์,3.246111,171.000000,63.611111,16.000000,2024-02-11
12,64013,บุญมี,20.000000,หญิง,วิศวกรรมศาสตร์,3.230000,169.000000,72.000000,24.000000,2024-01-06
13,64014,ปรีชา,21.000000,ชาย,ศิลปศาสตร์,3.450000,164.000000,54.000000,19.000000,2024-01-28
14,64015,พิมพ์,22.000000,หญิง,วิทยาศาสตร์,3.670000,162.000000,56.000000,26.000000,2024-01-09
15,64016,ภูมิ,19.000000,ชาย,วิทยาศาสตร์,3.890000,173.000000,78.000000,14.000000,2024-02-02
16,64017,มานี,20.000000,หญิง,วิศวกรรมศาสตร์,3.010000,166.000000,62.000000,21.000000,2024-01-11
17,64018,ยุพา,21.000000,หญิง,วิทยาศาสตร์,3.230000,161.000000,50.000000,27.000000,2024-02-12
18,64019,รัตนา,28.470588,ชาย,ศิลปศาสตร์,3.246111,174.000000,76.000000,21.388889,2024-01-26
19,64020,ลัดดา,22.000000,ชาย,วิทยาศาสตร์,3.450000,168.000000,64.000000,23.000000,2024-01-12

In [122]:

df['วันที่ลงทะเบียน'] = pd.to_datetime(df['วันที่ลงทะเบียน'])


df['วันในสัปดาห์'] = df['วันที่ลงทะเบียน'].dt.day_name()

แปลงคอลัมน์ 'วันที่ลงทะเบียน' เป็น datetime เเละ สร้างคอลัมน์ 'วันในสัปดาห์' โดยใช้ .dt.day_name()

In [123]:
df

,รหัสนักศึกษา,ชื่อ,อายุ,เพศ,คณะ,GPA,ส่วนสูง_cm,น้ำหนัก_kg,ชั่วโมงเรียน_ต่อสัปดาห์,วันที่ลงทะเบียน,วันในสัปดาห์
0,64001,สมชาย,20.000000,ชาย,วิทยาศาสตร์,3.210000,170.000000,65.000000,15.000000,2024-02-06,Tuesday
1,64002,สมหญิง,21.000000,หญิง,วิทยาศาสตร์,3.450000,165.000000,58.000000,20.000000,2023-12-17,Sunday
2,64003,ไม่ระบุ,28.470588,ชาย,วิทยาศาสตร์,3.670000,175.000000,63.611111,25.000000,2024-01-08,Monday
3,64004,สมศักดิ์,22.000000,ชาย,วิทยาศาสตร์,3.469591,168.000000,70.000000,10.000000,2024-01-28,Sunday
4,64005,สมใจ,19.000000,หญิง,วิศวกรรมศาสตร์,3.890000,160.000000,52.000000,30.000000,2024-01-14,Sunday
5,64006,กานต์,28.470588,ชาย,วิศวกรรมศาสตร์,3.120000,172.000000,75.000000,12.000000,2024-01-22,Monday
6,64007,กิตติ,21.000000,หญิง,วิศวกรรมศาสตร์,4.500000,158.000000,48.000000,35.000000,2023-12-17,Sunday
7,64008,จิรา,20.000000,หญิง,ศิลปศาสตร์,2.980000,180.000000,82.000000,18.000000,2024-02-13,Tuesday
8,64009,ชนาธิป,23.000000,ชาย,ศิลปศาสตร์,3.340000,163.000000,55.000000,22.000000,2024-01-05,Friday
9,64010,ดารา,21.000000,หญิง,ศิลปศาสตร์,3.560000,167.000000,60.000000,28.000000,2024-01-17,Wednesday
10,64011,ธีระ,28.470588,ชาย,วิทยาศาสตร์,3.780000,167.684211,68.000000,21.388889,2023-12-27,Wednesday
11,64012,นภา,22.000000,ชาย,วิทยาศาสตร์,3.246111,171.000000,63.611111,16.000000,2024-02-11,Sunday
12,64013,บุญมี,20.000000,หญิง,วิศวกรรมศาสตร์,3.230000,169.000000,72.000000,24.000000,2024-01-06,Saturday
13,64014,ปรีชา,21.000000,ชาย,ศิลปศาสตร์,3.450000,164.000000,54.000000,19.000000,2024-01-28,Sunday
14,64015,พิมพ์,22.000000,หญิง,วิทยาศาสตร์,3.670000,162.000000,56.000000,26.000000,2024-01-09,Tuesday
15,64016,ภูมิ,19.000000,ชาย,วิทยาศาสตร์,3.890000,173.000000,78.000000,14.000000,2024-02-02,Friday
16,64017,มานี,20.000000,หญิง,วิศวกรรมศาสตร์,3.010000,166.000000,62.000000,21.000000,2024-01-11,Thursday
17,64018,ยุพา,21.000000,หญิง,วิทยาศาสตร์,3.230000,161.000000,50.000000,27.000000,2024-02-12,Monday
18,64019,รัตนา,28.470588,ชาย,ศิลปศาสตร์,3.246111,174.000000,76.000000,21.388889,2024-01-26,Friday
19,64020,ลัดดา,22.000000,ชาย,วิทยาศาสตร์,3.450000,168.000000,64.000000,23.000000,2024-01-12,Friday

In [125]:
student_health = pd.DataFrame(df)


student_health['BMI'] = student_health['น้ำหนัก_kg'] / (student_health['ส่วนสูง_cm'] / 100) ** 2

คำนวณ BMI จากคอลัมน์ น้ำหนัก_kg และ ส่วนสูง_cm ใน DataFrame student_health และเพิ่มคอลัมน์ BMI ใหม่

In [126]:
student_health

,รหัสนักศึกษา,ชื่อ,อายุ,เพศ,คณะ,GPA,ส่วนสูง_cm,น้ำหนัก_kg,ชั่วโมงเรียน_ต่อสัปดาห์,วันที่ลงทะเบียน,วันในสัปดาห์,BMI
0,64001,สมชาย,20.000000,ชาย,วิทยาศาสตร์,3.210000,170.000000,65.000000,15.000000,2024-02-06,Tuesday,22.491349
1,64002,สมหญิง,21.000000,หญิง,วิทยาศาสตร์,3.450000,165.000000,58.000000,20.000000,2023-12-17,Sunday,21.303949
2,64003,ไม่ระบุ,28.470588,ชาย,วิทยาศาสตร์,3.670000,175.000000,63.611111,25.000000,2024-01-08,Monday,20.770975
3,64004,สมศักดิ์,22.000000,ชาย,วิทยาศาสตร์,3.469591,168.000000,70.000000,10.000000,2024-01-28,Sunday,24.801587
4,64005,สมใจ,19.000000,หญิง,วิศวกรรมศาสตร์,3.890000,160.000000,52.000000,30.000000,2024-01-14,Sunday,20.312500
5,64006,กานต์,28.470588,ชาย,วิศวกรรมศาสตร์,3.120000,172.000000,75.000000,12.000000,2024-01-22,Monday,25.351541
6,64007,กิตติ,21.000000,หญิง,วิศวกรรมศาสตร์,4.500000,158.000000,48.000000,35.000000,2023-12-17,Sunday,19.227688
7,64008,จิรา,20.000000,หญิง,ศิลปศาสตร์,2.980000,180.000000,82.000000,18.000000,2024-02-13,Tuesday,25.308642
8,64009,ชนาธิป,23.000000,ชาย,ศิลปศาสตร์,3.340000,163.000000,55.000000,22.000000,2024-01-05,Friday,20.700817
9,64010,ดารา,21.000000,หญิง,ศิลปศาสตร์,3.560000,167.000000,60.000000,28.000000,2024-01-17,Wednesday,21.513859
10,64011,ธีระ,28.470588,ชาย,วิทยาศาสตร์,3.780000,167.684211,68.000000,21.388889,2023-12-27,Wednesday,24.183802
11,64012,นภา,22.000000,ชาย,วิทยาศาสตร์,3.246111,171.000000,63.611111,16.000000,2024-02-11,Sunday,21.754082
12,64013,บุญมี,20.000000,หญิง,วิศวกรรมศาสตร์,3.230000,169.000000,72.000000,24.000000,2024-01-06,Saturday,25.209201
13,64014,ปรีชา,21.000000,ชาย,ศิลปศาสตร์,3.450000,164.000000,54.000000,19.000000,2024-01-28,Sunday,20.077335
14,64015,พิมพ์,22.000000,หญิง,วิทยาศาสตร์,3.670000,162.000000,56.000000,26.000000,2024-01-09,Tuesday,21.338211
15,64016,ภูมิ,19.000000,ชาย,วิทยาศาสตร์,3.890000,173.000000,78.000000,14.000000,2024-02-02,Friday,26.061679
16,64017,มานี,20.000000,หญิง,วิศวกรรมศาสตร์,3.010000,166.000000,62.000000,21.000000,2024-01-11,Thursday,22.499637
17,64018,ยุพา,21.000000,หญิง,วิทยาศาสตร์,3.230000,161.000000,50.000000,27.000000,2024-02-12,Monday,19.289379
18,64019,รัตนา,28.470588,ชาย,ศิลปศาสตร์,3.246111,174.000000,76.000000,21.388889,2024-01-26,Friday,25.102391
19,64020,ลัดดา,22.000000,ชาย,วิทยาศาสตร์,3.450000,168.000000,64.000000,23.000000,2024-01-12,Friday,22.675737

In [127]:
student_health['สุขภาพ'] = pd.cut(student_health['BMI'],
                                   bins=[0, 18.5, 25, 30, 100],
                                   labels=['ผอม', 'ปกติ', 'อ้วน', 'อ้วนมาก'])

pd.cut() ใช้สำหรับแบ่งข้อมูลในคอลัมน์ BMI เป็นช่วง ๆ ที่กำหนดใน bins และใช้ labels เพื่อกำหนดชื่อหรือป้ายให้กับแต่ละช่วง

ผลลัพธ์จะเป็นการสร้างคอลัมน์ สุขภาพ ที่มีค่าตาม BMI ของนักศึกษาใน DataFrame

In [129]:
student_health

,รหัสนักศึกษา,ชื่อ,อายุ,เพศ,คณะ,GPA,ส่วนสูง_cm,น้ำหนัก_kg,ชั่วโมงเรียน_ต่อสัปดาห์,วันที่ลงทะเบียน,วันในสัปดาห์,BMI,สุขภาพ
0,64001,สมชาย,20.000000,ชาย,วิทยาศาสตร์,3.210000,170.000000,65.000000,15.000000,2024-02-06,Tuesday,22.491349,ปกติ
1,64002,สมหญิง,21.000000,หญิง,วิทยาศาสตร์,3.450000,165.000000,58.000000,20.000000,2023-12-17,Sunday,21.303949,ปกติ
2,64003,ไม่ระบุ,28.470588,ชาย,วิทยาศาสตร์,3.670000,175.000000,63.611111,25.000000,2024-01-08,Monday,20.770975,ปกติ
3,64004,สมศักดิ์,22.000000,ชาย,วิทยาศาสตร์,3.469591,168.000000,70.000000,10.000000,2024-01-28,Sunday,24.801587,ปกติ
4,64005,สมใจ,19.000000,หญิง,วิศวกรรมศาสตร์,3.890000,160.000000,52.000000,30.000000,2024-01-14,Sunday,20.312500,ปกติ
5,64006,กานต์,28.470588,ชาย,วิศวกรรมศาสตร์,3.120000,172.000000,75.000000,12.000000,2024-01-22,Monday,25.351541,อ้วน
6,64007,กิตติ,21.000000,หญิง,วิศวกรรมศาสตร์,4.500000,158.000000,48.000000,35.000000,2023-12-17,Sunday,19.227688,ปกติ
7,64008,จิรา,20.000000,หญิง,ศิลปศาสตร์,2.980000,180.000000,82.000000,18.000000,2024-02-13,Tuesday,25.308642,อ้วน
8,64009,ชนาธิป,23.000000,ชาย,ศิลปศาสตร์,3.340000,163.000000,55.000000,22.000000,2024-01-05,Friday,20.700817,ปกติ
9,64010,ดารา,21.000000,หญิง,ศิลปศาสตร์,3.560000,167.000000,60.000000,28.000000,2024-01-17,Wednesday,21.513859,ปกติ
10,64011,ธีระ,28.470588,ชาย,วิทยาศาสตร์,3.780000,167.684211,68.000000,21.388889,2023-12-27,Wednesday,24.183802,ปกติ
11,64012,นภา,22.000000,ชาย,วิทยาศาสตร์,3.246111,171.000000,63.611111,16.000000,2024-02-11,Sunday,21.754082,ปกติ
12,64013,บุญมี,20.000000,หญิง,วิศวกรรมศาสตร์,3.230000,169.000000,72.000000,24.000000,2024-01-06,Saturday,25.209201,อ้วน
13,64014,ปรีชา,21.000000,ชาย,ศิลปศาสตร์,3.450000,164.000000,54.000000,19.000000,2024-01-28,Sunday,20.077335,ปกติ
14,64015,พิมพ์,22.000000,หญิง,วิทยาศาสตร์,3.670000,162.000000,56.000000,26.000000,2024-01-09,Tuesday,21.338211,ปกติ
15,64016,ภูมิ,19.000000,ชาย,วิทยาศาสตร์,3.890000,173.000000,78.000000,14.000000,2024-02-02,Friday,26.061679,อ้วน
16,64017,มานี,20.000000,หญิง,วิศวกรรมศาสตร์,3.010000,166.000000,62.000000,21.000000,2024-01-11,Thursday,22.499637,ปกติ
17,64018,ยุพา,21.000000,หญิง,วิทยาศาสตร์,3.230000,161.000000,50.000000,27.000000,2024-02-12,Monday,19.289379,ปกติ
18,64019,รัตนา,28.470588,ชาย,ศิลปศาสตร์,3.246111,174.000000,76.000000,21.388889,2024-01-26,Friday,25.102391,อ้วน
19,64020,ลัดดา,22.000000,ชาย,วิทยาศาสตร์,3.450000,168.000000,64.000000,23.000000,2024-01-12,Friday,22.675737,ปกติ